<?php

/**
 * Contacto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfAgenda
 * @subpackage model
 * @author     Flai Webnected S. L.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contacto extends BaseContacto
{
  
  protected $direccion_principal;
  protected $otras_direcciones = array();
  
  public function construct()
  {
    parent::construct();
    
    foreach($this->getDirecciones() as $direccion)
    {
      if( !$this->direccion_principal && $direccion->getPredeterminado() )
      {
        $this->direccion_principal = $direccion;
      }
      else
      {
        $this->otras_direcciones[] = $direccion;
      }
    }
  }
  
  public function getSlug()
  {
    $nombre_completo = sprintf("%s %s %s", $this->nombre, $this->primer_apellido, $this->segundo_apellido);

    return Doctrine_Inflector::urlize( $nombre_completo );
  }
  
  public function getDireccionPrincipal()
  {
    return $this->direccion_principal;
  }
  
  public function getOtrasDirecciones()
  {
    return $this->otras_direcciones;
  }

}
