<?php

/**
 * ContactoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactoTable extends Doctrine_Table
{

  public function masVisitados( $max_elementos )
  {
    return Doctrine_Query::create()
      ->from('Contacto')
      ->orderBy('visitas desc')
      ->limit( $max_elementos )
      ->execute();
  }

  /**
   * Returns an instance of this class.
   *
   * @return object ContactoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Contacto');
  }

}