<?php

/**
 * Contacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfAgenda
 * @subpackage model
 * @author     Flai Webnected S. L.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contacto extends BaseContacto
{
}
