<?php

/**
 * ContactoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contacto');
    }
}