# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: static, action: index }

listpage:
  url:   /busqueda
  param: { module: static, action: list }

detailpage:
  url:   /detalle
  param: { module: static, action: detail }

newpage:
  url:   /nuevo
  param: { module: static, action: new }

editpage:
  url:   /editar
  param: { module: static, action: edit }

deletepage:
  url:   /borrar
  param: { module: static, action: delete }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
